[package]
name = "blog"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.12.1"
axum = "0.8.1"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0" , features = ["rt-multi-thread"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
